name: React CI
on: [pull_request]

jobs:
  lint:
    name: Testing the PR
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.17.x]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Checkout node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm i
      - name: Running linter
        run: npm run lint
      - name: Running prettier
        run: npm run prettier
      - name: Running tests
        run: npm run test
      - name: Declaring env
        run: printf "DEV_SERVER_PORT=${{ secrets.DEV_SERVER_PORT }}\nNODE_ENV=${{ secrets.NODE_ENV }}\nLOG_ENABLED=${{ secrets.LOG_ENABLED }}\nALMIGHTY_USERS=${{ secrets.ALMIGHTY_USERS }}\nHOST_WEBSOCKET=${{ secrets.HOST_WEBSOCKET }}\nHOST_BLUEPRINT=${{ secrets.HOST_BLUEPRINT }}\nHOST_BLUEPRINT_API=${{ secrets.HOST_BLUEPRINT_API }}\nHOST_BLUEPRINT_PRO=${{ secrets.HOST_BLUEPRINT_PRO }}\nGDPR_ENV=${{ secrets.GDPR_ENV }}\nGDPR_API_KEY=${{ secrets.GDPR_API_KEY }}\nGDPR_APP_KEY=${{ secrets.GDPR_APP_KEY }}\nGDPR_API_HOST=${{ secrets.GDPR_API_HOST }}\nAUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}\nAUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}\nAUTH0_REALM=${{ secrets.AUTH0_REALM }}\nCHAT_REGION=${{ secrets.CHAT_REGION }}\nCHAT_APP_ID=${{ secrets.CHAT_APP_ID }}\nFONT_GENERATOR_URL=${{ secrets.FONT_GENERATOR_URL }}\nROLLBAR_PUBLIC_ACCESS_TOKEN=${{ secrets.ROLLBAR_PUBLIC_ACCESS_TOKEN }}\nSTRIPE_UK__ACCOUNT=${{ secrets.STRIPE_UK__ACCOUNT }}\nSTRIPE_UK__CLIENT_ID=${{ secrets.STRIPE_UK__CLIENT_ID }}\nSTRIPE_UK__CLIENT_KEY=${{ secrets.STRIPE_UK__CLIENT_KEY }}\nSTRIPE_US__ACCOUNT=${{ secrets.STRIPE_US__ACCOUNT }}\nSTRIPE_US__CLIENT_ID=${{ secrets.STRIPE_US__CLIENT_ID }}\nSTRIPE_US__CLIENT_KEY=${{ secrets.STRIPE_US__CLIENT_KEY }}\nFIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}\nFIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}\nFIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}\nFIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}\nFIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}\nFIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}\nFIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}\nFIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
      - name: Building app
        run: NODE_OPTIONS=--max-old-space-size=4096 npm run build
